"""Crear tabla RecurringSchedule y añadir FK a TripSchedule

Revision ID: f47522e53005
Revises: 
Create Date: 2025-10-18 21:23:28.347185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47522e53005'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=5), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route', 'day_of_week', 'time', name='_route_day_time_uc')
    )
    with op.batch_alter_table('trip_schedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_from_recurring_id', sa.Integer(), nullable=True))
        # AQUI LA CORRECCIÓN: 'None' se reemplaza por un nombre
        batch_op.create_foreign_key(
            'fk_trip_schedule_recurring_id', 
            'recurring_schedule', 
            ['created_from_recurring_id'], 
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_schedule', schema=None) as batch_op:
        # AQUI LA CORRECCIÓN: 'None' se reemplaza por el mismo nombre
        batch_op.drop_constraint(
            'fk_trip_schedule_recurring_id', 
            type_='foreignkey'
        )
        batch_op.drop_column('created_from_recurring_id')

    op.drop_table('recurring_schedule')
    # ### end Alembic commands ###